version: '3'
services:
    rancher:
        container_name: rancher
        ports:
            - 8064:80
            - 5443:443
        environment:
            - CATTLE_BOOTSTRAP_PASSWORD=voyour_password
        volumes:
            - /volume1/docker/rancher:/var/lib/rancher
        privileged: true
        restart: always
        image: rancher/rancher:latest